openapi: 3.0.0   # Open api version

info:   # Set basic infomation
  title: largest-prime-factor
  version: 1.0.0

servers:   # Set your server endpoint
  - url: https://master-largest-prime-factor-htcrefactor.endpoint.ainize.ai

paths:
  /:   # GET method path
    get:
      summary: Returns largest prime factor
      description: Returns largest prime factor
      parameters:   # Set parameter values here
        - name: number   # Set parameter name
          in: query   # Select amongst query, header, path, and cookie
          required: true
          allowReserved: false   # Option for percent-encoding, default; false
          schema:
            type: string
      responses:   # Set response
        '200':
          description: Successful Response
          content:   # Descriptions of potential response payloads (optional)
            text/plain:
              schema:   # Set data types
                type: object

        '400':
          description: Bad Request Error
        '500':
          description: Server-side Error
        '503':
          description: Server is not ready
        default: 
          description: Unexpected Error 
 